name: library-analyzer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - PyYAML
    - whoosh
    - sentence-transformers
    - torch
    - faiss-cpu
    - numpy
    - mistralai