name: library-analyzer
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - faiss-cpu
  - pip:
      - PyYAML
      - whoosh
      - sentence-transformers
      - numpy
      - mistralai
      - openai
